model_config_file: './configs/retinanet_config.yaml'
# ann_files: '/mnt/hdd1/datasets/coco/annotations/instances_train2017.json'
# root_img_dirs: '/mnt/hdd1/datasets/coco/images/train2017'
ann_files: '/data/datasets/coco/annotations/instances_train2017.json'
root_img_dirs: '/data/datasets/coco/images/train2017'

batch_size: 1
max_iter: 1440000
base_lr: 0.001
warmup_iters: 8000

# log_dir: '/mnt/hdd1/jobs/kindler_retinanet'
# checkpoint_dir: '/mnt/hdd1/jobs/kindler_retinanet/checkpoints'
log_dir: '/data/workspace/mingrui/Jobs/kindler_retinanet'
checkpoint_dir: '/data/workspace/mingrui/Jobs/kindler_retinanet/checkpoints'
