---
model_config_file: './configs/retinanet_config.yaml'
ann_files: 'path to instances_train201X'
root_img_dirs: 'path to images directory'

batch_size: 1
max_iter: 1440000
base_lr: 0.001
warmup_iters: 8000

min_image_size: 800
max_image_size: 1000

log_dir: './logs'
checkpoint_dir: './checkpoints'
